server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

storage:
  service:
    url: ${STORAGE_SERVICE_URL:http://localhost:8081}

analytics:
  service:
    url: ${ANALYTICS_SERVICE_URL:http://localhost:8082}